name: seodp
services:
  seodp:
    container_name: seodp
    env_file:
      - ./.env
    volumes:
      - "./service-account.json:/app/service-account.json"
      - "./seodpconfig.yaml:/app/seodpconfig.yaml"
      - "./seodp.db:/app/seodp.db"
    image: seodp
    command: --start
    restart: unless-stopped
